export const data = [
  {
    id: 1,
    name: "OKORO VICTOR",
    image: "img/avatar.jpg",
    track: "FRONTEND",
    score: 100 + "points",
  },
  {
    id: 2,
    name: "CHIBUEZE AKA",
    image: "img/avatar2.jpg",
    track: "UI / UX DESIGN",
    score: 95 + "points",
  },
  {
    id: 3,
    name: "AMARA ADA",
    image: "img/avatar6.jpg",
    track: "BACKEND",
    score: 90 + "points",
  },
  {
    id: 4,
    name: "CHARLES EZIKE",
    image: "img/avatar4.jpg",
    track: "WEB3",
    score: 90 + "points",
  },
  {
    id: 5,
    name: "CHUKWUEBUKA	ORIIH",
    image: "img/avatar5.jpg",
    track: "BACKEND",
    score: 89 + "points",
  },
  {
    id: 6,
    name: "OLA EDWARD",
    image: "img/avatar6.jpg",
    track: "UI / UX DESIGN",
    score: 85 + "points",
  },
  {
    id: 7,
    name: "MUSA AHMED",
    image: "img/avatar7.jpg",
    track: "FRONTEND",
    score: 80 + "points",
  },
  {
    id: 8,
    name: "DAN STONES",
    image: "img/avatar8.jpg",
    track: "WEB3",
    score: 70 + "points",
  },
  {
    id: 9,
    name: "CHIOMA UGWUODO",
    image: "img/avatar9.jpg",
    track: "FRONTEND",
    score: 70 + "points",
  },
  {
    id: 10,
    name: "ONYINYECHI OKEKE",
    image: "img/avatar10.jpg",
    track: "UI / UX DESIGN",
    score: 69 + "points",
  },
  {
    id: 11,
    name: "CHINYERE	AKANNO",
    image: "img/avatar11.jpg",
    track: "WEB3",
    score: 60 + "points",
  },
  {
    id: 12,
    name: "NANCY OKEKE",
    image: "img/avatar2.jpg",
    track: "BACKEND",
    score: 50 + "points",
  },
  {
    id: 14,
    name: "IFEANYI ATTAH",
    image: "img/avatar4.jpg",
    track: "WEB3",
    score: 50 + "points",
  },
  {
    id: 15,
    name: "JONATHAN	AMOBI",
    image: "img/avatar5.jpg",
    track: "UI / UX DESIGN",
    score: 50 + "points",
  },
  {
    id: 16,
    name: "MOSES NJOKU",
    image: "img/avatar6.jpg",
    track: "BACKEND",
    score: 50 + "points",
  },
  {
    id: 17,
    name: "PAUL	OLISAELOKA",
    image: "img/avatar7.jpg",
    track: "FRONTEND",
    score: 45 + "points",
  },
  {
    id: 18,
    name: "MICHAEL	ORJI",
    image: "img/avatar8.jpg",
    track: "WEB3",
    score: 40 + "points",
  },
  {
    id: 19,
    name: "CHIOMA UGWUODO",
    image: "img/avatar9.jpg",
    track: "UI / UX DESIGN",
    score: 40 + "points",
  },
];
